name: doom_breaker
description: "A Flutter productivity app with authentication and user onboarding."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Supabase (replaces Firebase)
  supabase_flutter: ^2.0.0
  google_sign_in: ^6.1.6
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Permissions
  permission_handler: ^11.3.0
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  android_intent_plus: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
